name: rllab3
channels:
    - https://conda.anaconda.org/soumith
    - https://conda.anaconda.org/kne
    - https://conda.anaconda.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
dependencies:
    - python==3.6.3
    # - scipy
    # - mako
    # - path.py
    # - pybox2d
    # - pygame
    - theano
    - pygpu
    - pip
    # - joblib
    - pip:
        - boto3
        - cached_property
        - cloudpickle
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/rll/rllab.git
        - gym==0.9.3
        - https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp36-cp36m-linux_x86_64.whl
        - matplotlib
        - mujoco-py==0.5.7
        - numpy
        - pyglet==1.3.2
        - pyprind
        - torch==1.6.0
        - torchvision
        # uncomment if want to plot on server
        # - pyvirtualdisplay
        # - xvfbwrapper==0.2.9
        - yapf
        - wandb
