name: rllab3
channels:
    - https://conda.anaconda.org/soumith
    - https://conda.anaconda.org/kne
    - https://conda.anaconda.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
dependencies:
    - python==3.6.3
    # - scipy
    # - mako
    # - path.py
    # - pybox2d
    # - pygame
    - theano
    - pygpu
    - pip
    # - joblib
    - pip:
        - https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
        # - torchvision
        # - numpy
        # - gym==0.9.3
        # - mujoco-py==0.5.7
        # - matplotlib
        # - cached_property
        # - pyprind
        # - boto3
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
          # https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.11.0-gpu-10.0_7.3_5.0-mkl/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp36-cp36m-linux_x86_64.whl
        # - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp36-cp36m-manylinux2010_x86_64.whl
        - git+https://github.com/rll/rllab.git
        # - cloudpickle
